export const ROUTERS = {
  HOME: 'HOME',
  PRODUCTS: 'PRODUCTS',
  SPLASHSCREEN: 'SPLASHSCREEN',
  SIGNIN: 'SIGNIN',
  MAINSTACK: 'MAINSTACK',
  AUTHSTACK: 'AUTHSTACK',
  INTROSCREEN: 'INTROSCREEN',
};
